export const Users = [
    {
        id: 1,
        profilePicture: "assets/1.png",
        username: "Safak Kocaoglu",
    },
    {
        id: 2,
        profilePicture: "assets/1.png",
        username: "Janell Shrum",
    },
    {
        id: 3,
        profilePicture: "assets/1.png",
        username: "Alex Durden",
    },
    {
        id: 4,
        profilePicture: "assets/1.png",
        username: "Dora Hawks",
    },
    {
        id: 5,
        profilePicture: "assets/1.png",
        username: "Thomas Holden",
    },
    {
        id: 6,
        profilePicture: "assets/1.png",
        username: "Shirley Beauchamp",
    },
    {
        id: 7,
        profilePicture: "assets/1.png",
        username: "Travis Bennett",
    },
    {
        id: 8,
        profilePicture: "assets/1.png",
        username: "Kristen Thomas",
    },
    {
        id: 9,
        profilePicture: "assets/1.png",
        username: "Gary Duty",
    },
    {
        id: 10,
        profilePicture: "assets/1.png",
        username: "Safak Kocaoglu",
    },
];

export const u = [
    {
        id: 1,
        profilePicture: "default.png",
        username: "Safak Kocaoglu",
        name: "Safak Kocaoglu",
        bio: "Safak Kocaoglu",
        phone: "Safak Kocaoglu",
        email: "Safak Kocaoglu",
        job: "Safak Kocaoglu",
    },
];
export const Posts = [
    {
        id: 1,
        post: "Love For All, Hatred For None.",
        photo: "assets/1.png",
        date: "5 mins ago",
        userId: 1,
        react: 32,
        comment: 9,
    },
    {
        id: 2,
        photo: "assets/1.png",
        date: "15 mins ago",
        userId: 2,
        react: 2,
        comment: 1,
    },
    {
        id: 3,
        post: "Every moment is a fresh beginning.",
        photo: "assets/1.png",
        date: "1 hour ago",
        userId: 3,
        react: 61,
        comment: 2,
    },
    {
        id: 4,
        photo: "assets/1.png",
        date: "4 hours ago",
        userId: 4,
        react: 7,
        comment: 3,
    },
    {
        id: 5,
        photo: "assets/1.png",
        date: "5 hours ago",
        userId: 5,
        react: 23,
        comment: 5,
    },
    {
        id: 6,
        photo: "assets/1.png",
        date: "1 day ago",
        userId: 6,
        react: 44,
        comment: 6,
    },
    {
        id: 7,
        post: "Never regret anything that made you smile.",
        photo: "assets/1.png",
        date: "2 days ago",
        userId: 7,
        react: 52,
        comment: 3,
    },
    {
        id: 8,
        photo: "assets/1.png",
        date: "3 days ago",
        userId: 8,
        react: 15,
        comment: 1,
    },
    {
        id: 9,
        post: "Change the world by being yourself.",
        photo: "assets/1.png",
        date: "5 days ago",
        userId: 9,
        react: 11,
        comment: 2,
    },
    {
        id: 10,
        photo: "assets/1.png",
        date: "1 week ago",
        userId: 10,
        react: 104,
        comment: 12,
    },
];
